Solve the the issue of non-DVB transport stream(TS) which using the PID, 0x10~0x1F, as the PIDs of the video/audio streams of program
asticode/go-astits pull request #54
Opened 2023-10-13 01:09 UTC by jlnieh

###  Scenario

We got the sample transport stream from IPTV source, which using the PID 0x10 as the program PID, 0x11 as the video stream PID, and 0x12 as the audio stream PID. The transport stream would cause the PSI checksum error, while we tried to use the demux to get **NextData()** of the stream.

### ISO Standard

According to the **Table 2-3 -- PID table** of the standard ISO/IEC 13818-1:2007, the PID range 0x0010~0x1FFE may be assigned as network PID, program map PID, elementary_PID, or for other purposes.

### Changes

1. Use existed struct **programMap** to setup the locks of the PIDs which used in the program already
2. While demux **parseData()**, use the locks to avoid the used PIDs of elementary streams to be identified as PSI table.

2023-10-15 09:51 UTC, asticode commented
Which type of content are you demuxing (you say non-DVB, but what's the exact type?) and how can we identify it as non-DVB?

2023-10-17 02:50 UTC, jlnieh commented
> Which type of content are you demuxing (you say non-DVB, but what's the exact type?) and how can we identify it as non-DVB?

I believe it is following the ATSC standard or just the IPTV transport stream which does not use those DVB metadata, NIT or SDT.  It is not easy to identify the transport stream is following which standard, since both DVB and ATSC standards have their own specific PIDs for their system tables . I would suggest 

1. add one more option to NewDemuxer to let user/developer to choose the TS standard, OR
2. in this case, we could demux the transport stream based on the PAT and known PMT to identify those PIDs, 0x0010~0x001F, is used or locked by one known program/service, OR
3. in parsePSIData(), if we got the table ID, which is not reasonable, for example the table ID 0x00 is coming with the non-zero PID, we should stop and fall back to identify this PID is non-PSI and may parse it as the PES or some kind of private data in the following packets.

2023-10-17 09:49 UTC, asticode commented
OK thanks for the clarification 👍 

In that case I would rather you add a new `elementaryStreamMap`, similar to `programMap` but separated from it. You can use the same function names.

2023-10-24 08:20 UTC, jlnieh commented
Updated to add a new `elementaryStreamMap`. Please check.

2023-10-29 09:22 UTC, asticode requested changes

2023-10-29 09:22 UTC, asticode commented on stream_map.go
> +func (m elementaryStreamMap) setLocked(pid, number uint16) {
Could you rename `Locked` to `Unlocked` in all 3 functions?

The idea is to let the developer know the function is not locking any mutex while manipulating the map which is really unsafe.

2023-10-29 09:22 UTC, asticode commented on data_test.go
> +	assert.True(t, isPSIPayload(uint16(1), pm, esm))
Could you add a test using `esm.setUnlocked()` like it was done with `pm.setUnlocked(uint16(1), uint16(0))` above?

2023-10-29 09:22 UTC, asticode commented on data_test.go
> +	ds, err = parseData(ps, nil, pm, esm)
Could you add a test using `esm.setUnlocked()` like it was done with `pm.setUnlocked(uint16(256), uint16(1))` above?

2023-10-29 09:22 UTC, asticode commented on demuxer.go
> +	streamMap    *elementaryStreamMap
Could you order fields alphabetically?

2025-04-22 03:45 UTC, sylwek78 approved these changes

2026-08-12 21:03 UTC, benjamin-knight-sai commented
Hi @asticode I am trying to revisit this PR as it seems to be the root cause of the errors I was experiencing here https://github.com/bluenviron/mediamtx/issues/6059

Excuse my ignorance as I am quite new to all these concepts of networking, video processing, etc. 

I have a UDP multicast of MPEG-TS coming in that is using the PID `0x0011` for the H.264 video 
<img width="1214" height="594" alt="image" src="https://github.com/user-attachments/assets/f28f8a63-8dcf-44dd-9456-0076feb000ee" />

Which is declared in the PMT as the video stream
<img width="1463" height="571" alt="image" src="https://github.com/user-attachments/assets/bc477c00-eb32-4707-a7a8-6e8d1a6ac69c" />

It seems like the library is declaring packets with the `0x0011` PID as PSI before caring about the PMT declaration which later causes errors and MediaMTX to fail to ingest the video. I was able to forward the changes in this PR from @jlnieh onto a more recent version of go-astits, rebuild MediaMTX with it, which solved my issue.

Is there anything I can do to help get this PR merged in?

2026-08-13 06:48 UTC, asticode commented
Sure, I've made 4 remarks that need to be addressed before being able to merge this PR. If you address them, I'll be able to merge this PR 👍

2026-08-13 16:43 UTC, ben8622 commented
@asticode I have put up a new PR with your comments addressed https://github.com/asticode/go-astits/pull/77

2026-08-14 07:12 UTC, closed without merging